##use App\Controller\HomeController;
#use App\Controller\RegistrationController;
controllers:
    resource: ../src/Controller/
    type: attribute
 # config/routes.yaml

home:
    path: /
    controller: App\Controller\HomeController::index
# connexion au formulaire d'inscription
#registration:
    #path: /register
   # controller: App\Controller\RegistrationController::register

# connexion au formulaire d'inscription réussie
#registration_success:
   # path: /register/success
   # controller: App\Controller\RegistrationController::success
